### ISSUE TITLE
Expose User firstName, photo, and countryCode in Reportback Items endpoint 

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/api#7]
Phoenix Reportback Item endpoint needs to display the [User photo for each Reportback Item](https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Discovery/Campaign%20Detail.png).

One possible approach:
- Sync Northstar User photo to Phoenix User photo
- Expose user photo in Phoenix reportback items endpoint

**Comment by aaronschachter** [comment]
@uy We'll also need the same for User countryCode.

**Comment by aaronschachter** [comment]
The user's first name should be included in this endpoint as well.

**Comment by chloealee** [comment]
@aaronschachter since we're moving user info out of drupal, can we just make reportback items endpoint request this info from northstar and append it to the response that gets sent to you? :)

**Comment by mshmsh5000** [comment]
We could lazy-load these from Northstar and cache them on the Drupal side with a reasonable timeout (e.g., 24 hrs).

**Comment by angaither** [comment]
@mshmsh5000 confused, are you saying we lazy load user profiles images from Northstar into drupal? or just cache them with the response drupal returns

**Comment by mshmsh5000** [comment]
I assume we're talking about returning a URL to the user's profile image, correct?

What I'm suggesting is, while assembling a report back (WARNING: pseudo-code and fake German to follow):

```
/**
 * Das functionne
 */
function assemble_reportback($rbid) {
  // ...
  $user = $rb->user;
  $profile_image_url = northstar_get_profile_image($user);
  // ...
}

/**
 * Das lazy loaden-werk
 */
function northstar_get_profile_image($user) {
  $profile_image_url = cache_get('northstar_profile_image_' . $user->uid);

  if (empty($profile_image_url)) {
    $profile_image_url = actually_load_image_url_from_northstar($user);

    if (empty($profile_image_url)) {
      throw new NorthstarDataException("All of the people in your party have died.");
    }

    $cache_set('northstar_profile_image_' . $user->uid, $profile_image_url, 'cache', REQUEST_TIME + 60*60*24);
  }

  return $profile_image_url;
}
```

**Comment by weerd** [comment]
More exceptions should use language like this: `"All of the people in your party have died."` lol

**Comment by chloealee** [comment]
:+1: thanks everyone!

**Comment by aaronschachter** [comment]
We still need the User's Country and First Name though too.  Currently we store Country in Phoenix through the `field_address` mega-field.

**Comment by aaronschachter** [comment]
Also worth noting there is a very small of users who will already have a `photo` property set -- it's what's displayed in the "Created by" modal.  It's an edge case, but for Member Created Campaigns.. its possible those Users would download and use the app.
