### ISSUE TITLE
Northstar User campaigns endpoint needs to return https url for Reportback Item images

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/api#9]
https://github.com/DoSomething/LetsDoThis-iOS/issues/455#issuecomment-145619714

iOS9 wants all things https. I'm querying the User's `campaigns` on https but get http returned in the results:

See `users/email/vanna.white%40dosomething.org/campaigns` for staging northstar

![screen shot 2015-10-05 at 2 10 32 pm](https://cloud.githubusercontent.com/assets/1236811/10291332/41c93d84-6b77-11e5-9a9f-b61a9fbe1666.png)

**Comment by jonuy** [comment]
@angaither @weerd @chloealee any of you happen to know how the `http` protocol is set in the uri's returned?

**Comment by weerd** [comment]
Hmmm, not really sure. Might be an argument we pass to Drupal methods when generating some of those URLs. I can look into it from the Phoenix side.

**Comment by jonuy** [comment]
@weerd @aaronschachter This was an issue on the Northstar side. I needed to change an environment variable so that Northstar was making requests against Phoenix with `https`. This should be fixed now.

**Comment by weerd** [comment]
So we can close this @jonuy ?

**Comment by jonuy** [comment]
I didn't actually check it with an iOS build, so might be worth checking there first. @aaronschachter when you get around to it, would you be able to check and close this out if we're good?

**Comment by aaronschachter** [comment]
Looks good!
